spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: lishuai

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


logging:
  level:
    root: warn
    com.lishuai: info
  file: log/blog-pro.log

server:
  port: 8081